### ISSUE TITLE
Segmentation fault on af on a big function.

### ISSUE THREAD

**Issue by 0pendev** [radareorg/radare2#15507]
# Work environment

Questions | Answers
-- | --
OS/arch/bits (mandatory) | openSUSE Tumbleweed x86_64
File format of the file you reverse (mandatory) | ELF
Architecture/bits of the file (mandatory) | x64
r2 -v full output, not truncated (mandatory) | radare2 4.1.0-git 23310 @ linux-x86-64 git.4.0.0-132-g9c08b9e4c commit: 9c08b9e4c02ec49c3c789760504c8ae4461a7c20 build: 2019-11-26__08:22:54

# Expected behavious
The command `af bigfunction 4198793` should analyse my function.

# Actual behaviour
`
/home/myuser/Softwares/radare2/env.sh: line 65:  4681 Segmentation fault      (core dumped) R2_ENV_IS_SET=1 R2_LIBR_PLUGINS=${pfx}/lib/radare2 PATH=$pfx/bin:${PATH} LD_LIBRARY_PATH=$pfx/lib:$LD_LIBRARY_PATH DYLD_LIBRARY_PATH=$pfx/lib:$DYLD_LIBRARY_PATH PKG_CONFIG_PATH=$pfx/lib/pkgconfig:$PKG_CONFIG_PATH "${1}" "${2}"
`
# Steps to reproduce the behaviour
I've been stucked at : 
```bash
r2 ./binary
e anal.depth =0x1400
af bigfunction 4198793
```

It does not give me the full function if I try with e anal.depth=0x1300 for example.

# Additional Logs, screenshots, source-code, configuration dump, ...
The binary is to big for github so I've put it [here](http://challenge01.root-me.org/cracking/ch34/ch34.xz).

**Comment by DCNick3** [comment]
The link to the binary gives `Not Found` for me

**Comment by 0pendev** [comment]
@DCNick3,  Sorry the link expired. Here is an [updated one](https://framadrop.org/r/w_Wk-orhdf#Z8LMPcz6Jb6NngdDSv9UCJvjqyG2GMH1MhBB+9+IDsY=).

**Comment by radare** [comment]
Probably fixed in the anal-blocks branch

**Comment by 0pendev** [comment]
Just tested on branch anal-blocks. It isn't fixed.

**Comment by radare** [comment]
@thestr4ng3r chk this issue pls

**Comment by thestr4ng3r** [comment]
@0pendev link is dead again

**Comment by thestr4ng3r** [comment]
This should be fixed on master now.

**Comment by radare** [comment]
🎉

**Comment by 0pendev** [comment]
@thestr4ng3r ,
Just tested it. It still isn't working for me. I just passed the depth to 0x1500 and I've got the same issue. (the function is not fully analysed with a depth of 0x1400).

**Comment by 0pendev** [comment]
No news about this issue ?

**Comment by radare** [comment]
I think we can close it

**Comment by thestr4ng3r** [comment]
I don't think so, it seems to be still present.

**Comment by radare** [comment]
Then it should be fixed. Didnt tried yet

**Comment by XVilka** [comment]
@thestr4ng3r @0pendev can you please reupload binary? The link is dead again?

**Comment by 0pendev** [comment]
Reuploaded it [here](https://catdrop.drycat.fr/r/QgS7tFsg#QaCyGcuySduom2r2bpfJWmza3uUd4c8kM5P1EQCzVO4=)

**Comment by XVilka** [comment]
@trufae you asked - it's here now: http://xvilka.me/ch34.xz

**Comment by trufae** [comment]
Thanks @XVilka 

This is an stack exhaustion issue because everytime there's a JMP it calls recursively the same analysis function and this program seems to have a lot of small jumps going forward all the time.

To fix this we need to rewrite the function to use an iterative design instead. Here's the backtrace:

![Screenshot 2020-07-07 at 10 43 16](https://user-images.githubusercontent.com/6431515/86751026-ac555400-c03e-11ea-83dc-37a82fe6f9de.png)

as you see the addr parameter is always different and moving forward, so it can't catch the end position. So imho i would move this to 4.6 because rewriting the analysis will require some more work and this is just affecting obfuscated big binaries like this.

Also im seeing some other patterns in this executable that may trick the analysis so it requires some extra work, an option would be to remove trash code somehow and patch the binary before analyzing it , but this is not an option in some situations, so this must be addressed too.

![Screenshot 2020-07-07 at 10 49 35](https://user-images.githubusercontent.com/6431515/86752325-8ed4ba00-c03f-11ea-87e1-1ab6e344138a.png)

**Comment by trufae** [comment]
Please try again

**Comment by trufae** [comment]
Closing, as there's no feedback and the bin is not there, but many related bugs has been addressed.
