### ISSUE TITLE
Outdated plugins improvements

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#15803]
```
Module version mismatch /home/dude/.local/share/radare2/plugins/core_pdd.so (4.1.0-git) vs (4.2.0-git)
```
* maybe we can add another field in the r2 plugins
* to specify which command to run to update the plugin
* and prompt the user to rebuild it in case of outdated

**Comment by radare** [comment]
Done in master

**Comment by cryptax** [comment]
This still occurs. 
I tried both `sys/install.sh` and `sys/user.sh` to update radare2, and at first launch, got:
 `module version mismatch /home/axelle/.local/share/radare2/plugins/core_pdd.so (3.0.0-git) vs (5.3.1)`.
 I got no message / warning during install.
 
 I expected `r2pm update` to solve the issue. It did not.
```
$ r2pm update
Module version mismatch /home/axelle/.local/share/radare2/plugins/core_pdd.so (3.0.0-git) vs (5.3.1)
HEAD is now at 91e0eb8 Update db/radeco (#76)
remote: Enumerating objects: 715, done.
remote: Counting objects: 100% (715/715), done.
remote: Compressing objects: 100% (357/357), done.
remote: Total 635 (delta 343), reused 531 (delta 277), pack-reused 0
Receiving objects: 100% (635/635), 87.64 KiB | 3.02 MiB/s, done.
Resolving deltas: 100% (343/343), completed with 77 local objects.
From https://github.com/radare/radare2-pm
   e752900..e2c9996  master     -> origin/master
Updating 91e0eb8..e2c9996
Fast-forward
 README.md             | 20 ++++++--------------
 db/agc                |  2 +-
 db/apktool            | 17 +++++++++++++++++
...
 create mode 100644 db/vdexextractor
 create mode 100644 env.sh
Updating /home/axelle/.local/share/radare2/r2pm/db ...
Already up to date.
$ r2 --version
Module version mismatch /home/axelle/.local/share/radare2/plugins/core_pdd.so (3.0.0-git) vs (5.3.1)
```

I had to issue `r2pm install r2dec` explicitly to **solve the problem**.
So, now it works, but perhaps indeed, there's some missing documentation or improvement to do.

**Comment by trufae** [comment]
@cryptax i have added `r2pm upgrade` to actually run the commands suggested by r2 when trying to load old plugins installed via r2pm. That may solve those warnings next time (but it only works for plugins compiled against r2 >= 4.2.0
