### ISSUE TITLE
How to convert data to as address offset 

### ISSUE THREAD

**Issue by lynnux** [radareorg/radare2#18175]
This is from IDA: ![图片](https://user-images.githubusercontent.com/367894/103634741-7ad42b80-4f82-11eb-9305-f0d2a40c5f13.png)
And this is from cutter:
![图片](https://user-images.githubusercontent.com/367894/103634879-a820d980-4f82-11eb-9d43-2cb794e248e1.png)
I'm newbee to radare, and don't how to specific data to addr offset type.

**Comment by trufae** [comment]
Just pick the dword menuitem. Or use the Cd4 command in r2

**Comment by lynnux** [comment]
@trufae thank you for quick reply, but this only convert to dword value, not the address
```
0x10053878      .dword 0x1004bf3c         // this point to "ov" string address
0x1005387c      .dword 0x10007790        // this point to a call function
0x10053880      .dword 0x1004bf40
0x10053884      .dword 0x10007830
0x10053888      .dword 0x1004bf44
0x1005388c      cmp     byte [ebx], 0x10
0x10053890      dec     eax
...
```
btw, 0x10053878 is in `.data` section, the permission of .data is `-rw-`, don't have `x`, so I think radare should not treat `.data` as code section. IDA show the zero bytes in `.data` as:
```
.data:100548B7                 db    ? ;
.data:100548B8                 db    ? ;
.data:100548B9                 db    ? ;
.data:100548BA                 db    ? ;
.data:100548BB                 db    ? ;
.data:100548BC                 db    ? ;
```
and cutter show as:
```
0x100548b7      add     byte [eax], al
0x100548b9      add     byte [eax], al
0x100548bb      add     byte [eax], al
0x100548bd      add     byte [eax], al
0x100548bf      add     byte [eax], al
0x100548c1      add     byte [eax], al
0x100548c3      add     byte [eax], al
```
and there are many 4bytes data should be treat as address pointer like me showed in above.

**Comment by trufae** [comment]
Dwords are resolved as offsets if they are valid so this is what you have to do.

Can you share the binary? I think you are trying to disassemble some regions filled by relocs which require io.cache to be set. Can you blind try r2 -e io.cache=1 ... ?

R2 treats everything as code by default. Ida does the inverse. But r2 can also behave like ida if you want. The problem is rhat usually you want to read code without analyzing, and finding data in code is easier than finding code in data

**Comment by lynnux** [comment]
this is the binary:
[bin.zip](https://github.com/radareorg/radare2/files/5774092/bin.zip)
I tried `r2 -e io.cache=1 ...`, use command `s 10053878` and `pd`, it's still the same.
btw, `10053878` is refered by `10006E90`, the follows are from IDA:
```
.text:10006E90 loc_10006E90:                           ; CODE XREF: xl_cmp_functions+4D↓j
.text:10006E90                 mov     ecx, cmp_table[esi*8]        // cmp_table is a symbol renamed by me
.text:10006E97                 mov     eax, edi
.text:10006E99                 nop     dword ptr [eax+00000000h]
.text:10006EA0
```
in r2, it's:
```
[0x10006e90]> pd
        .-> 0x10006e90      8b0cf5783805.  mov ecx, dword [esi*8 + 0x10053878]
        :   0x10006e97      8bc7           mov eax, edi
        :   0x10006e99      0f1f80000000.  nop dword [eax]
       .--> 0x10006ea0      8a11           mov dl, byte [ecx]
```

**Comment by trufae** [comment]
Works perfectly for me. but you need to define the string in the 4bf3c and set a flag in the cmptable place, the reason why this is not happening by default is probably because 3 char strings are discarded to avoid false positives.

![Screenshot 2021-05-27 at 13 16 37](https://user-images.githubusercontent.com/6431515/119817051-c5ccec00-beed-11eb-9662-14da9e160dc7.png)
![Screenshot 2021-05-27 at 13 16 45](https://user-images.githubusercontent.com/6431515/119817065-ca91a000-beed-11eb-8ec2-082c51541729.png)
