### ISSUE TITLE
x86 16bit invalid long call/jump segment:offset display

### ISSUE THREAD

**Issue by lasek0** [radareorg/radare2#18888]
## Environment

```sh
$ date
r2 -v
uname -mswto, 6 lip 2021, 00:26:05 CEST
$ radare2 5.4.0-git 26743 @ linux-x86-64 git.5.3.1
commit: 9d6afad8b2e2d964e3e7cef598403640120c9cb9 build: 2021-07-05__23:24:16
$ 

```

## Description

x86 16bit invalid long call/jump segment:offset display. this bug is wired sometimes works sometimes output is invalid.
Please notice that same address can be shown correctly and incorrectly at same time, example 9ad3010500.

## Test

```
[0000:0000]> pd 9999~lcall
```
or
```
[0000:0000]> pd 9999~ljmp
```

this shows invalid:
```
│           0000:0cc1      9a56015c00     lcall 0x5c0x156            
│           0000:0d38      9a34015c00     lcall 0x5c0x134              
│           0000:0d48      9ad3010500     lcall 50x1d3                
│           0000:0d58      9ad3010500     lcall 50x1d3                
│           0000:0d6d      9af4010500     lcall 50x1f4                                
```
```
│    │││    0000:04b7      ea00000500     ljmp 50                    
│           0000:060d      ea04000000     ljmp 04
│           0000:0843      ea04000000     ljmp 04      
```

this shows OK:
```
            0000:2ac7      9a76017d00     lcall 0x7d:0x176            
            0000:2af3      9ad3010500     lcall 5:0x1d3                
            0000:2b06      9ad3010500     lcall 5:0x1d3               
            0000:2b1f      9af4010500     lcall 5:0x1f4                
            0000:2b3d      9af4010500     lcall 5:0x1f4               
            0000:2b5d      9a4c09cb00     lcall 0xcb:0x94c             

```

**Comment by trufae** [comment]
I think this should be fixed now, can you confirm?

**Comment by lasek0** [comment]
Sorry but problem still appear. need to reopen.
tried to fix by self but takes too much time, maybe this is something wrong with esil,
and probably easy for You to fix, or please point me where to try fix that.

x86-16 bit call address with segment:base displayed wrong when bytes are analysed as function.

env:
$ date
pią, 14 sty 2022, 17:07:07 CET
$ r2 -v
radare2 5.5.5 27722 @ linux-x86-64 git.5.5.4
commit: 4a3db2a1cdc723fc130543c022335d0ea03a8696 build: 2022-01-14__17:05:36
$ uname -ms
Linux x86_64

example:
$r2 -

e asm.arch=x86
e asm.bits=16
e asm.seggrn=8
e anal.jmp.tbl=false
s 0x0
wx 558bec83ec7256579a660152005f5ec9cb @ 0x0
pd 10
af
pdf

my output:
[0x00000000]> e asm.arch=x86
[0x00000000]> e asm.bits=16
[0000:0000]> e asm.seggrn=8
[0000:0000]> e anal.jmp.tbl=false
[0000:0000]> s 0x0
[0000:0000]> wx 558bec83ec7256579a660152005f5ec9cb @ 0x0
[0000:0000]> pd 10
            0000:0000      55             push bp
            0000:0001      8bec           mov bp, sp
            0000:0003      83ec72         sub sp, 0x72
            0000:0006      56             push si
            0000:0007      57             push di
            0000:0008      9a66015200     lcall 0x52:0x166
            0000:000d      5f             pop di
            0000:000e      5e             pop si
            0000:000f      c9             leave
            0000:0010      cb             retf
[0000:0000]> af
[0000:0000]> pdf
┌ 17: fcn.00000000 ();
│           0000:0000      55             push bp
│           0000:0001      8bec           mov bp, sp
│           0000:0003      83ec72         sub sp, 0x72
│           0000:0006      56             push si
│           0000:0007      57             push di
│           0000:0008      9a66015200     lcall 0x52
│           0000:000d      5f             pop di
│           0000:000e      5e             pop si
│           0000:000f      c9             leave
└           0000:0010      cb             retf
[0000:0000]>

![Screenshot from 2022-01-14 17-11-40](https://user-images.githubusercontent.com/79937932/149548079-7f0feb2e-96dd-4020-96db-6fb11b3be0a0.png)
