### ISSUE TITLE
radiff2 crashes on new style iOS Kernelcaches in graph mode

### ISSUE THREAD

**Issue by littlelailo** [radareorg/radare2#19541]
## Environment

```sh
Sun Dec 26 19:55:14 CET 2021
radare2 5.5.5 27557 @ darwin-x86-64 git.5.5.4
commit: 3b04d3ef4093dafeff72e22589a3598ca0202ac9 build: 2021-12-26__19:53:05
Darwin x86_64
```

## Description

Radiff2 will segfault on an infinite recursion bug when you diff two kernel function in graph mode on new style iOS Kernelcaches.
The infinite recursion occurs in [kernelcache_io_read](https://github.com/radareorg/radare2/blob/master/libr/bin/p/bin_xnu_kernelcache.c#L1989):
```
  * frame #0: 0x0000000100d3988b libr_bin.dylib`kernelcache_io_read(io=0x0000000104864c00, fd=0x0000600005ad6380, buf="", count=4) at bin_xnu_kernelcache.c:2036:10
    frame #1: 0x0000000100d3988d libr_bin.dylib`kernelcache_io_read(io=0x0000000104864c00, fd=0x0000600005ad6380, buf="", count=4) at bin_xnu_kernelcache.c:2036:10
[...]
    frame #74851: 0x0000000100d3988d libr_bin.dylib`kernelcache_io_read(io=0x0000000104864c00, fd=0x0000600005ad6380, buf="", count=4) at bin_xnu_kernelcache.c:2036:10
    frame #74852: 0x0000000100d3988d libr_bin.dylib`kernelcache_io_read(io=0x0000000104864c00, fd=0x0000600005ad6380, buf="", count=4) at bin_xnu_kernelcache.c:2036:10
    frame #74853: 0x00000001003069e7 libr_io.dylib`r_io_plugin_read(desc=0x0000600005ad6380, buf="", len=4) at io_plugin.c:161:9
    frame #74854: 0x000000010030958b libr_io.dylib`r_io_desc_read(desc=0x0000600005ad6380, buf="", len=4) at io_desc.c:213:12
    frame #74855: 0x000000010030e53b libr_io.dylib`r_io_fd_read(io=0x0000000104864c00, fd=3, buf="", len=4) at io_fd.c:24:15
    frame #74856: 0x000000010050317b libr_util.dylib`buf_io_read(b=0x0000600008b4c360, buf="", len=4) at buf_io.c:72:9
    frame #74857: 0x00000001005007a1 libr_util.dylib`buf_read(b=0x0000600008b4c360, buf="", len=4) at buf.c:46:27
    frame #74858: 0x0000000100500084 libr_util.dylib`r_buf_read(b=0x0000600008b4c360, buf="", len=4) at buf.c:453:11
    frame #74859: 0x00000001004ffe99 libr_util.dylib`r_buf_read_at(b=0x0000600008b4c360, addr=0, buf="", len=4) at buf.c:603:6
    frame #74860: 0x0000000100d410d1 libr_bin.dylib`check_buffer(bf=0x0000000000000000, buf=0x0000600008b4c360) at bin_xtr_dyldcache.c:17:2
    frame #74861: 0x0000000100bb2572 libr_bin.dylib`r_bin_open_buf(bin=0x0000000101133cc0, buf=0x0000600008b4c360, opt=0x00007ff7bfefef80) at bin.c:273:8
    frame #74862: 0x0000000100bb22e7 libr_bin.dylib`r_bin_open_io(bin=0x0000000101133cc0, opt=0x00007ff7bfefef80) at bin.c:346:13
    frame #74863: 0x00000001009d085b libr_core.dylib`r_core_file_do_load_for_io_plugin(r=0x0000000102478000, baseaddr=18446744073709551615, loadaddr=0) at cfile.c:434:7
    frame #74864: 0x00000001009ced5e libr_core.dylib`r_core_bin_load(r=0x0000000102478000, filenameuri=0x0000000000000000, baddr=18446744073709551615) at cfile.c:635:4
    frame #74865: 0x0000000100823e5e libr_main.dylib`opencore(ro=0x00007ff7bfeff518, f="/tmp/kernel") at radiff2.c:88:10
    frame #74866: 0x0000000100822b91 libr_main.dylib`r_main_radiff2(argc=5, argv=0x00007ff7bfeff710) at radiff2.c:1139:8
    frame #74867: 0x0000000100003f82 radiff2`main(argc=5, argv=0x00007ff7bfeff710) at radiff2.c:6:9
    frame #74868: 0x00000001000154fe dyld`start + 462
```
The problem occurs in line [2036](https://github.com/radareorg/radare2/blob/master/libr/bin/p/bin_xnu_kernelcache.c#L2036) where the function calls itself. I assumed that maybe I could fix the code by checking if the functions are the same (like it's done in the if above), but that just resulted in a different crash (null deref):
```c
2035         }
2036         if (fd->plugin->read == &kernelcache_io_read) {return -1;}
2037         return fd->plugin->read (io, fd, buf, count);
```
```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0xf8)
    frame #0: 0x0000000100d39627 libr_bin.dylib`kernelcache_io_read(io=0x0000000105045c00, fd=0x0000600005bfbe40, buf="", count=4) at bin_xnu_kernelcache.c:2002:19
   1999		RBinFile *bf;
   2000		r_list_foreach (core->bin->binfiles, iter, bf) {
   2001			if (bf->fd == fd->fd ) {
-> 2002				cache = bf->o->bin_obj;
   2003				if (pending_bin_files) {
   2004					RListIter *to_remove = r_list_contains (pending_bin_files, bf);
   2005					if (to_remove) {
Target 0: (radiff2) stopped
```

## Test

Download an OTA update from Apple to get a kernelcache (we will use an OTA instead of an IPSW because they are smaller and we will only use one to download faster):
```sh
$ curl https://updates.cdn-apple.com/2021FCSFall/patches/002-26167/B62D4A95-3049-4D8C-8DEF-F28F722830FE/com_apple_MobileAsset_SoftwareUpdate/75fbbfe23d7ff5e9c2501bbad36461fbee17377b.zip > 14.8.1.zip 
```
Extract the kernelcache from it and decompress it using [jtool2](http://www.newosxbook.com/tools/jtool2.tgz):
```sh
$ unzip 14.8.1.zip AssetData/boot/kernelcache.release.iphone12c  
$ cd AssetData/boot/
$ jtool2 -dec kernelcache.release.iphone12c  
```
Then run radiff2 on it:
```sh
$ radiff2 -g 0xfffffff0081b44e8,0xfffffff0081b44f0 /tmp/kernel /tmp/kernel 
reconstructing chained fixups
reconstructing chained fixups
[...]
reconstructing chained fixups
zsh: segmentation fault  radiff2 -g 0xfffffff0081b44e8,0xfffffff0081b44f0 /tmp/kernel /tmp/kernel
```

This does not happen with old style kernel caches (like https://updates.cdn-apple.com/2021FCSFall/patches/002-26400/3FC386EB-AD1C-4500-8B50-E471435E1BED/com_apple_MobileAsset_SoftwareUpdate/7d346c8362340899517f7bf062f502558b7af22f.zip)

**Comment by trufae** [comment]
Sorry for the late response, busy days, should be fixed in this PR, but i would like a review from @mrmacete as long as he wrote the plugin and he will know better the implications of those added checks. The second bug is an infinite call recursion whichs results in a stack exhaustion problem. Thanks for reporting and happy 2022!

**Comment by mrmacete** [comment]
the fix solves the crash but the result is still incorrect because `check_buffer` fails for the second file. that's because "swizzling" the io read function is hacky and isn't robust when opening multiple files, because they all share the same io plugin
