### ISSUE TITLE
Out of memory when using r- command with seeking

### ISSUE THREAD

**Issue by richardpl** [radareorg/radare2#24325]
## Environment

```sh
# copypaste this script into your shell and replace it with the output
Thu Jun 19 17:29:35 UTC 2025
radare2 5.9.9 34075 @ linux-x86-64
birth: git.5.9.8-756-gbe6a57690b 2025-06-19__16:48:34
commit: be6a57690b42ba4fa1b0906281288230904a7b8f
options: gpl -O? cs:5 cl:2 make
Linux x86_64
```

## Description

sometimes r- (truncating size of binary does not work) and when it works it will leak exponentially memory.
>25GB in few seconds.

## Test

With enough big file (> 36M):

run this:

r- 304 @@s:0x0800 0x022b97a0 2048

Beware, this will usually trigger OOM killer on Linux.

The command just removes 304 bytes and skips 2048 bytes, unitl it reaches end offset.

**Comment by trufae** [comment]
Nice catch. Will chk asap but i pushed a pr adding early returns just in case that improves the situation. But i need to understand better the problem before pushing the right fix

**Comment by richardpl** [comment]
It does not help with OOM and crash, error is probably also how EOF is handled.
The instruction should abort when EOF is reached, in above command I have not take into account that each iteration make file smaller and thus command as is will reach out of file somewhere in middle of iterations. The command works fine if I limit 'to' paramater to sane value (the one guaranteed to be always inside file/memory)

**Comment by richardpl** [comment]
Hmm, looks like checking EOF does not help, it still leaks memory a lot - in each iteration.

**Comment by richardpl** [comment]
Now it aborts after first iteration, thus removes only first 304 bytes, but expected result is to continue removing 304 bytes and seeking 2048 forward until current EOF.

**Comment by trufae** [comment]
uhm im busy with other issues. can you give it a try to fix it? adding a test and base with the changes i made in [76ea049](https://github.com/kokizzu/radare2/commit/76ea049310eddb5b0cbffea79ff82a1bc4cda6d1)

**Comment by richardpl** [comment]
Will try, I encountered numerous memory leaks, that was not present last time I work on r2, so that may slow down me even more.

**Comment by trufae** [comment]
i fixed some of them, feel free to submit prs fixing the rest if you have time and interest

**Comment by trufae** [comment]
i fixed many other memleaks. is there anything else anoying you to take a look at this?

**Comment by richardpl** [comment]
I was busy with other projects, i might look it if time permits soon.

**Comment by richardpl** [comment]
I still see gross leaks, just for using V mode and scrolling in hex view up/down few times and then exiting - nothing complicated or useful.

**Comment by trufae** [comment]
Oh i didnt tried this workflow. Can you take a look at them? Ill have some spare time next week otherwise

**Comment by trufae** [comment]
ping? i cant repro

**Comment by richardpl** [comment]
It still removes only in first iteration and immediately aborts more iterations processing.

``r-64 @@s:0x80 0x8000 0x100``

What have you tested that works?

**Comment by trufae** [comment]
I was refering to the memory leaks sorry.

**Comment by richardpl** [comment]
That have been either resolved (so not that gross) or completely masked by early exit in first iteration cycle.

**Comment by trufae** [comment]
can you try https://github.com/radareorg/radare2/pull/24584 if that works like you expect now? otherwise i would appreciate if you could spend some time and submit a pr i dont more time to spend enough focus on the over 9000 tasks i do every day in parallel

**Comment by richardpl** [comment]
Appears to work correctly now, it works out through all iterations.

**Comment by trufae** [comment]
Good. Thanks for confirming! Ill fix the tests and merge
