### ISSUE TITLE
The "px/" command doesn't seem to work

### ISSUE THREAD

**Issue by jduck** [radareorg/radare2#4903]
```
[0x7f96b9f2b3d0]> sr rsp
[0x7ffd4a13af20]> px
- offset -       0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x7ffd4a13af20  0100 0000 0000 0000 08b6 134a fd7f 0000  ...........J....
0x7ffd4a13af30  0000 0000 0000 0000 10b6 134a fd7f 0000  ...........J....
...
[0x7ffd4a13af20]> px/24wx
[0x7ffd4a13af20]> px/4wx
[0x7ffd4a13af20]> px/2wx
...
```

**Comment by radare** [comment]
Never used wx in my whole life. I just implemented the pretty few ones i use. Feel free to add it if you find it necessary. This command is just for gdb compat

**Comment by radare** [comment]
In fact its designed to be used like x/... Like gdb does . This works because x is an alias for px

**Comment by trufae** [comment]
This issue is still there, i think it would be nice to support the gdb syntax for hex/disasm, we already support few of them. What do you think @XVilka @ret2libc ? otherwise having an incomplete implementration may lead to confusion, frustration and desperation to the users

**Comment by ret2libc** [comment]
Yes this would be nice. Let's add it for 4.6.0
